"use client";

import { Rubik } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "react-query";
import { AuthContextProvider } from "./context/AuthContext";

const rubik = Rubik({
  weight: "400",
  subsets: ["latin"],
});
const queryClient = new QueryClient();

// export const metadata = {
//   title: "Interactive Comments Section",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <AuthContextProvider>
          <body className={`${rubik.className} bg-[#f5f6fa] `}>{children}</body>
        </AuthContextProvider>
      </QueryClientProvider>
    </html>
  );
}
